Início

Levantar do sofá
Caminhar até a cozinha 
ir até a geladeira
se a porta da geladeira estiver fechada então
    abrir porta da geladeira
fimse
Pegar a garrafa de suco 
Pegar o copo ao lado da geladeira
Enxer o copo com suco
Tomar o suco
Colocar dentro da pia
Caminhar até o quarto
se porta fechada então
    abrir porta
fimse
Entrar no quarto
Fechar a porta do quarto
Ir até o armario
Abrir a gaveta 
Pegar o unico livro
Se o livro estiver empoeirado
    Passar a mao e remover a peoira
fimse
Abrir a porta
Sair do quarto
Fechar a porta
Caminhar até o sofa
Colocar o livro ao lado
Se televisao estiver ligada
    Entao desligar a televisao
fimse
Sentar no sofá

Fim
